# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'BreakingSnooze' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BreakingSnooze
	pod 'View2ViewTransition’
 	pod 'p2.OAuth2', '~> 3.0'

end
